<a href="https://colab.research.google.com/github/Mustafalw02/Machine-Learning-Lab-Work/blob/master/Neural_network_for_Mnist_number_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#Loading-the-MNIST-dataset-in-Keras" data-toc-modified-id="Loading-the-MNIST-dataset-in-Keras-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Loading the MNIST dataset in Keras</a></span></li><li><span><a href="#The-network-architecture" data-toc-modified-id="The-network-architecture-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The network architecture</a></span></li><li><span><a href="#The-compilation-step" data-toc-modified-id="The-compilation-step-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>The compilation step</a></span></li><li><span><a href="#Preparing-the-image-data" data-toc-modified-id="Preparing-the-image-data-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Preparing the image data</a></span></li><li><span><a href="#Preparing-the-labels" data-toc-modified-id="Preparing-the-labels-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Preparing the labels</a></span></li><li><span><a href="#Training-and-Testing" data-toc-modified-id="Training-and-Testing-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Training and Testing</a></span></li></ul></div>

# Loading the MNIST dataset in Keras

In [43]:
from keras.datasets import mnist

In [44]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

- The images are encoded as Numpy arrays, and the labels are an array of digits, ranging from 0 to 9.

In [45]:
train_images.shape


(60000, 28, 28)

In [46]:
len(train_labels)

60000

In [47]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [48]:
test_images.shape

(10000, 28, 28)

In [49]:
len(test_labels)

10000

In [50]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Let's build the network

# The network architecture

- The core building block of neural networks is the **layer**, a data-processing module that you can think of as a filter for data.
    - Some data goes in, and it comes out in a more useful form.
    - Layers extract **representations** (hopefully, meaningful for the data problem at hand) out of the data fed into them.
    
- Most of deep learning consists of chaining together simple layers that will implement a form of progressive **data distillation**.
- A deep learning model is like a sieve for data-processing, made of a succession of increasingly refined data filters--**the layers**.

In [51]:
from keras import models
from keras import layers

In [52]:
network = models.Sequential()
# Dense(512) is a fully-connected layer with 512 hidden units.
# in the first layer, you must specify the expected input data shape :
# here, 28 X 28=784 -dimensional vectors.
network.add(layers.Dense(32, activation='relu', input_shape=(28 * 28, )))
network.add(layers.Dense(16, activation='tanh'))
network.add(layers.Dense(10, activation='softmax'))

- Our network consists of a sequence of two *Dense* layers, which are densely connected (also called *fully connected*) neural layers.
- The second (and last) layer is a **10-way** *softmax* layer, which means it will return an array of **10** probability scores. Each score will be the probability that the current digit image belongs to one of our 10 digit classes. 

# The compilation step

- To make the network ready for training, we need to pick three more things, as part of the **compilation** step:
 - **A loss function**-- How the network will be able to measure its performance on the training data, and thus how it will be able to steer itself in the right direction.
 - **An optimizer**--The mechanism through which the network will update itself based on the data it sees and its loss function.
 - **Metrics to monitor during training and testing**--Here, we will only care about accuracy (the fraction of the images that were correctly classified).

In [53]:
network.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])
    

# Preparing the image data

Before training, we will preprocess the data by reshaping it into the shape the network expects and scaling it so that all values are in the $[0-1]$ interval.

In [54]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255.

In [55]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255.

# Preparing the labels

We also need to categorically encode the labels.

In [56]:
from tensorflow.keras.utils import to_categorical

In [57]:
train_labels = to_categorical(train_labels)
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [58]:
test_labels = to_categorical(test_labels)
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Training and Testing

We are now ready to train the network, which in Keras is done via a call to the network's fit method--we fit the model to its training data:

In [59]:
network.fit(train_images, train_labels, epochs=20, batch_size=64)

Epoch 1/20
938/938 [==============================] - 4s 4ms/step - loss: 0.4760 - accuracy: 0.8853
Epoch 2/20
938/938 [==============================] - 3s 4ms/step - loss: 0.2000 - accuracy: 0.9441
Epoch 3/20
938/938 [==============================] - 3s 4ms/step - loss: 0.1479 - accuracy: 0.9574
Epoch 4/20
938/938 [==============================] - 3s 4ms/step - loss: 0.1191 - accuracy: 0.9661
Epoch 5/20
938/938 [==============================] - 3s 4ms/step - loss: 0.1013 - accuracy: 0.9704
Epoch 6/20
938/938 [==============================] - 3s 4ms/step - loss: 0.0892 - accuracy: 0.9739
Epoch 7/20
938/938 [==============================] - 3s 4ms/step - loss: 0.0794 - accuracy: 0.9769
Epoch 8/20
938/938 [==============================] - 3s 4ms/step - loss: 0.0720 - accuracy: 0.9787
Epoch 9/20
938/938 [==============================] - 3s 4ms/step - loss: 0.0657 - accuracy: 0.9809
Epoch 10/20
938/938 [==============================] - 3s 4ms/step - loss: 0.0610 - accuracy: 0.9819

- Two quantities are displayed during training:
    - The loss of the network over the training data
    - The accuracy of the network over the training data
    
- We quickly reach an accuracy of **$0.9886 (98.86\%)$** on the training data.

- Now let's check that the model performs well on the test set, too:

In [60]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.1112 - accuracy: 0.9712


In [61]:
print('Test Accuracy: {:.5f} '.format(test_acc))

Test Accuracy: 0.97120 


In [62]:
test_acc

0.9711999893188477

- The test-set accuracy turns out to be $97.780\%$--that is quite a bit lower than the training set accuracy. This gap between training and test accuracy is an example of **overfitting**:the fact that the ML models tend to perform worse on new data than on their training data.

In [64]:
from keras.utils import plot_model
plot_model(network, to_file='model.png')

ImportError: ignored

In [ ]:
import matplotlib.pyplot as plt
history =network.fit(train_images, train_labels, validation_split=0.33,epochs=20, batch_size=64)
history_dict = history.history
print(history_dict.keys())
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

Epoch 1/20
629/629 [==============================] - 4s 6ms/step - loss: 0.0304 - accuracy: 0.9909 - val_loss: 0.0463 - val_accuracy: 0.9848
Epoch 2/20
629/629 [==============================] - 5s 8ms/step - loss: 0.0272 - accuracy: 0.9922 - val_loss: 0.0367 - val_accuracy: 0.9881
Epoch 3/20
629/629 [==============================] - 5s 8ms/step - loss: 0.0235 - accuracy: 0.9937 - val_loss: 0.0400 - val_accuracy: 0.9870
Epoch 4/20
629/629 [==============================] - 4s 6ms/step - loss: 0.0225 - accuracy: 0.9942 - val_loss: 0.0404 - val_accuracy: 0.9873
Epoch 5/20
629/629 [==============================] - 4s 6ms/step - loss: 0.0193 - accuracy: 0.9950 - val_loss: 0.0402 - val_accuracy: 0.9877
Epoch 6/20
629/629 [==============================] - 3s 5ms/step - loss: 0.0193 - accuracy: 0.9949 - val_loss: 0.0483 - val_accuracy: 0.9842
Epoch 7/20
629/629 [==============================] - 4s 6ms/step - loss: 0.0169 - accuracy: 0.9960 - val_loss: 0.0538 - val_accuracy: 0.9831
Epoch 